version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  io_stardewmit-message:
    # Prefix all io_stardewmit messages with "Changed: "
    prefix: "Changed"
