# Gradle Settings
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.caching=true
android.suppressUnsupportedCompileSdk=35

# Android Settings
android.useAndroidX=true
android.enableJetifier=true

# Kotlin Settings
kotlin.code.style=official

# Release Versions
RELEASE_VERSION_NAME=0.1
RELEASE_VERSION_CODE=1

# Beta Versions
BETA_VERSION_NAME=0.1.10-beta
BETA_VERSION_CODE=110

# Debug Versions
DEBUG_VERSION_NAME=0.1.110-debug
DEBUG_VERSION_CODE=1110
